// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odosaalpddimejppnvjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kb3NhYWxwZGRpbWVqcHBudmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Nzc5NjAsImV4cCI6MjA2MDI1Mzk2MH0.UVBE6vnLelAMc491H19yY62aKfjsOYkankWxV7DBA64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);